### ISSUE TITLE
Digest::Digest is deprecated; use Digest

### ISSUE THREAD

**Issue by bsedat** [engineyard/ey_api_hmac#3]
I'm seeing a warning coming from this gem when upgrading to Ruby MRI 2.1.1. 
Seems to be related to https://github.com/engineyard/ey_api_hmac/blob/master/lib/ey_api_hmac.rb#L46.

**Comment by jacobo** [comment]
fixed by https://github.com/engineyard/ey_api_hmac/commit/bce918712c99cc61060f55c512fbe4747f4c9ea4

**Comment by jacobo** [comment]
0.4.11 gem released

**Comment by bsedat** [comment]
Thanks!
